apiVersion: v1
kind: Service
metadata:
  name: nginx-loadbalancer
  namespace: service-demo
  labels:
    app: nginx
    service-type: loadbalancer
  annotations:
    # AWS负载均衡器配置示例
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # GCP负载均衡器配置示例
    # cloud.google.com/neg: '{"exposed_ports": {"80":{}}}'
spec:
  selector:
    app: nginx
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer